// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkaJUEN-lY6WrneJoSfhILkEDUYiPf48c',
    appId: '1:1084947863540:web:cd97a5cfa6ad975f1d8ba1',
    messagingSenderId: '1084947863540',
    projectId: 'periodtracker-2b90f',
    authDomain: 'periodtracker-2b90f.firebaseapp.com',
    storageBucket: 'periodtracker-2b90f.firebasestorage.app',
    measurementId: 'G-51BH7C611R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDOwWuWSVbKyBLNZoOFCLEJ0D0i9_vwM',
    appId: '1:1084947863540:android:0c160ef4edecd9391d8ba1',
    messagingSenderId: '1084947863540',
    projectId: 'periodtracker-2b90f',
    storageBucket: 'periodtracker-2b90f.firebasestorage.app',
  );
}
